# Generated by Django 2.1.2 on 2018-11-19 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favouritearticle',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='favouritearticle',
            name='email',
        ),
        migrations.AddField(
            model_name='favouritearticle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
