# Generated by Django 2.1.1 on 2018-10-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerating',
            name='avg_rating',
        ),
    ]
