# Generated by Django 2.1.1 on 2018-10-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
