# Generated by Django 2.1.1 on 2018-10-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tagList',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
