# Generated by Django 2.1.1 on 2018-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
