# Generated by Django 2.1.1 on 2018-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20181003_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.URLField(db_index=True, max_length=255),
        ),
    ]
